spring:
  cloud:
    config:
      # enabled: true
      server:
        git:
          uri: https://github.com/bjxPolestar/config-repo.git
          search-paths: config-repo/dev-*
          #临时存储路径
          basedir: ../config-repo-temp
          username: *****
          password: ****
          force-pull: true #配置中心通过git从远程git库，有时本地的拷贝被污染，这时配置中心无法从远程库更新本地配置,设置force-pull=true，则强制从远程库中更新本地库
          default-label: master
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: *
    password: *